name: CI

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: BUILD
    uses: adamkubon/reusable-workflow/.github/workflows/reusable-workflow.yaml@main
    permissions:
      actions: read
    concurrency:
      # cancels in-progress jobs on pull_request events only
      group: build
      cancel-in-progress: true
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
    with:
      param1: ${{ inputs.param1 }}

  # Telemetry job runs after all other jobs complete
  telemetry:
    runs-on: ubuntu-latest
    needs: [build] # Wait for other jobs to complete
    if: always() # Run even if other jobs fail
    steps:

      - name: Wait for job finish
        id: wait
        run:
          sleep 5

      - name: Send Telemetry
        uses: paper2/github-actions-opentelemetry@main
        env:
          OTEL_SERVICE_NAME: github-actions-opentelemetry
          OTEL_EXPORTER_OTLP_ENDPOINT: https://telemetry.googleapis.com
          # Additional OTLP headers. Useful for OTLP authentication.
          # e.g.
          # New Relic: api-key=YOUR_NEWRELIC_API_KEY
          # Google Cloud Run: Authorization=Bearer <value of $(gcloud auth print-identity-token)>
          # Basic Authentication: Authorization=Basic <base64-encoded value of userid:password>
          OTEL_EXPORTER_OTLP_HEADERS:
            api-key=${ secrets.API_KEY },other-config-value=value
          OTEL_RESOURCE_ATTRIBUTES: 'environment=ci,team=backend'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}