name: Reusable CI workflow

on:
  workflow_call:

jobs:
  build:
    name: Reusable CI workflow
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
    steps:

      - name: Repository checkout
        id: checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          show-progress: false
          persist-credentials: 'false'

      - name: Build
        id: build
        shell: bash
        run: |
          echo "BUILD PHASE"

      - name: Test phase
        id: test
        shell: bash
        run: |
          echo "Test phase"

  # Telemetry job runs after all other jobs complete
  telemetry:
    runs-on: ubuntu-latest
    needs: [build] # Wait for other jobs to complete
    if: always() # Run even if other jobs fail
    steps:
      - name: Wait for job finish
        id: wait
        run:
          sleep 300

      - name: Send Telemetry
        uses: paper2/github-actions-opentelemetry@main
        env:
          OTEL_SERVICE_NAME: github-actions-opentelemetry
          OTEL_EXPORTER_OTLP_ENDPOINT: https://telemetry.googleapis.com
          # Additional OTLP headers. Useful for OTLP authentication.
          # e.g.
          # New Relic: api-key=YOUR_NEWRELIC_API_KEY
          # Google Cloud Run: Authorization=Bearer <value of $(gcloud auth print-identity-token)>
          # Basic Authentication: Authorization=Basic <base64-encoded value of userid:password>
          OTEL_EXPORTER_OTLP_HEADERS:
            api-key=${ secrets.API_KEY },other-config-value=value
          OTEL_RESOURCE_ATTRIBUTES: 'environment=ci,team=backend'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}