name: Reusable CI workflow

on:
  workflow_call:
    inputs:
      param1:
        required: true
        type: string
        default: 'value1'
        description: 'important param'

jobs:
  build:
    name: Reusable CI workflow
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
    steps:

      - name: Repository checkout
        id: checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          show-progress: false
          persist-credentials: 'false'

      - name: Build
        id: build
        shell: bash
        run: |
          echo "BUILD PHASE: ${{ inputs.param1 }}"

      - name: Test phase
        id: test
        shell: bash
        run: |
          echo "Test phase"
